const ENV = {
  API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  API_HEADER_X_TENANT_DOMAIN: process.env.REACT_APP_API_HEADER_X_TENANT_DOMAIN,
  API_HEADER_X_API_VERSION: process.env.REACT_APP_API_HEADER_X_API_VERSION,
  API_HEADER_X_APP_TYPE: process.env.REACT_APP_API_HEADER_X_APP_TYPE,

  TENANT_ID: process.env.REACT_APP_TENANT_ID,
  PATIENT_ROLE: process.env.REACT_APP_PATIENT_ROLE,
  PRACTICE_ID: process.env.REACT_APP_PATIENT_PRACTICE_ID,

  RACE_FIELD_ID: process.env.REACT_APP_RACE_FIELD_ID,
  ETHNICITY_FIELD_ID: process.env.REACT_APP_ETHNICITY_FIELD_ID,
  CUSTOM_FIELD_AREA_USER_PROFILE:
    process.env.REACT_APP_CUSTOM_FIELD_AREA_USER_PROFILE,

  COLLECTOR_DEVICE_DATA_MODEL_ID:
    process.env.REACT_APP_COLLECTOR_DEVICE_DATA_MODEL_ID,
  READER_DEVICE_DATA_MODEL_ID:
    process.env.REACT_APP_READER_DEVICE_DATA_MODEL_ID,
  DEVICE_PROPERTY_SET_ID: process.env.REACT_APP_DEVICE_PROPERTY_SET_ID,
};

export default ENV;
