export default {
  patients: [
    {
      id: "1",
      firstName: "John",
      middleName: "",
      lastName: "Doe",
      dateOfBirth: "1989-05-24",
      gender: "male",
      race: "",
      ethnicity: "",
      email: "john.doe@gmail.com",
      phoneNumber: "1123453234",
      streetAddress1: "Wallstreet",
      city: "New York",
      state: "New York",
      zipCode: "58100",
    },
    {
      id: "2",
      firstName: "Jane",
      middleName: "",
      lastName: "Ayre",
      dateOfBirth: "1989-05-24",
      gender: "male",
      race: "",
      ethnicity: "",
      email: "jane.ayre@gmail.com",
      phoneNumber: "1123453234",
      streetAddress1: "Wallstreet",
      city: "New York",
      state: "New York",
      zipCode: "58100",
    },
  ],
};
